#Accelerometers
accelerometer_noise_density: 8.0e-02   #Noise density (continuous-time)
accelerometer_random_walk:   4.0e-05   #Bias random walk

#Gyroscopes
gyroscope_noise_density:     1.2e-02   #Noise density (continuous-time)
gyroscope_random_walk:       4.0e-06   #Bias random walk

rostopic:                    /imu0      #the IMU ROS topic
update_rate:                 238.0      #Hz (for discretization of the values above)

